export const START_FETCH_MOVIES = "START_FETCH_MOVIES";
export const SUCCESS_FETCH_MOVIES = "SUCCESS_FETCH_MOVIES";
export const FAIL_FETCH_MOVIES = "FETCH_MOVIES_FAIL";
export const START_FETCH_MOVIE = "START_FETCH_MOVIE";
export const SUCCESS_FETCH_MOVIE = "SUCCESS_FETCH_MOVIE";
export const FAIL_FETCH_MOVIE = "FAIL_FETCH_MOVIE";
